CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    cpf VARCHAR(14) UNIQUE,
    endereco VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS pets (
    id_pet BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    especie VARCHAR(30) NOT NULL,
    raca VARCHAR(50),
    cliente_id BIGINT REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agendamentos (
    id_agendamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT REFERENCES pets(id_pet) ON DELETE CASCADE,
    servico VARCHAR(30) NOT NULL CHECK (servico IN ('Banho', 'Tosa', 'Banho e Tosa', 'Outros')),
    data_servico DATE NOT NULL,
    horario_servico TIME NOT NULL,
    status VARCHAR(30) DEFAULT 'Agendado' CHECK (status IN ('Agendado', 'Em Andamento', 'Concluido', 'Concluído', 'Cancelado')),
    observacao TEXT
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);
